name:                A
version:             0.1.0.0
github:              "deech/A"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"

extra-source-files:
- README.md
- ChangeLog.md

custom-setup:
  dependencies:
  - base >= 4.4
  - Cabal >= 1.24.1 && < 3
  - asset-bundle

data-files:
- ./A.txt
description:         Please see the README on Github at <https://github.com/deech/A#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - B
  - C

executables:
  A-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - A
